In [4]:
import numpy as np

np.iinfo(np.dtype('uint32'))

iinfo(min=0, max=4294967295, dtype=uint32)

In [7]:
(255 << 24) + (255 << 16) + (255 << 8) + 255, 4294967295

(4294967295, 4294967295)

In [8]:
import numpy as np

a = np.array([
    [True, False, False],
    [False, True, True],
    [False, False, True]
])

[(r, c) for r, c in np.argwhere(a)]
a.ndim

2

In [2]:
from src.camera import ConwaysGOLCamera
import numpy as np
from timeit import default_timer

s = 2000
a1 = (np.random.rand(s, s) > 0.4).astype(int)
a2 = np.copy(a1)

print("Starting")

camera = ConwaysGOLCamera(start_state=a1, array_package='numpy')
camera.update(None, None, force_update=True)
t = default_timer()
for i in range(10):
    camera.update(None, None, force_update=True)
t1 = default_timer() - t

print("Numpy: %.4f" % t1)

camera = ConwaysGOLCamera(start_state=a1, array_package='torch-cpu')
camera.update(None, None, force_update=True)
t = default_timer()
for i in range(10):
    camera.update(None, None, force_update=True)
t1 = default_timer() - t

print("Torch-cpu: %.4f" % t1)

camera = ConwaysGOLCamera(start_state=a1, array_package='torch-gpu')
camera.update(None, None, force_update=True)
t = default_timer()
for i in range(10):
    camera.update(None, None, force_update=True)
t1 = default_timer() - t

print("Torch-gpu: %.4f" % t1)

camera = ConwaysGOLCamera(start_state=a1, array_package='cupy')
camera.update(None, None, force_update=True)
t = default_timer()
for i in range(10):
    camera.update(None, None, force_update=True)
t1 = default_timer() - t

print("cupy: %.4f" % t1)

Starting
Numpy: 1.7300
Torch-cpu: 0.9958
Torch-gpu: 0.0264
cupy: 0.0434


In [ ]:
import numpy as np

In [10]:
import numpy as np

a = np.array([
    [0, 1, 0],
    [0, 1, 1],
    [1, 1, 0],
])

vals = np.argwhere(a == 1)

print(a)
print(vals)
print(a[vals[:, 0], vals[:, 1]])

[[0 1 0]
 [0 1 1]
 [1 1 0]]
[[0 1]
 [1 1]
 [1 2]
 [2 0]
 [2 1]]
[1 1 1 1 1]


In [6]:
import torch

a = torch.tensor([
    [1, 0, 1, 1, 0],
    [1, 0, 0, 1, 0],
    [1, 0, 1, 0, 0],
    [1, 1, 1, 1, 0],
], dtype=torch.int32).to('cuda:0')

f = torch.ones((3, 3), dtype=torch.float32).to('cuda:0')

torch.round(torch.nn.functional.conv2d(a.unsqueeze(0).unsqueeze(0), f.unsqueeze(0).unsqueeze(0))[0][0]).type(torch.int32)

RuntimeError: Input type (torch.cuda.IntTensor) and weight type (torch.cuda.FloatTensor) should be the same

In [25]:
import numpy as np

c = np.array([
    [0, 1, 0],
    [0, 1, 1],
    [1, 1, 0],
])
nc = np.array([
    [2, 3, 3],
    [4, 5, 4],
    [3, 4, 3],
])
# (~c & (nc == 3)) | (c & (3 <= nc <= 4))
np.logical_and(np.logical_not(c), nc == 3)

array([[False, False,  True],
       [False, False, False],
       [False, False,  True]])

In [27]:
import torch

c = torch.tensor([
    [0, 1, 0],
    [0, 1, 1],
    [1, 1, 0],
])
nc = torch.tensor([
    [2, 3, 3],
    [4, 5, 4],
    [3, 4, 3],
])

torch.logical_not()

tensor([[-1, -2, -1],
        [-1, -2, -2],
        [-2, -2, -1]])